# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: GeeCON Krakow 2025
email: ""
description: "Let's move the Java world!"
baseurl: "/geecon-2015-mobile"
url: "http://geecon.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "GeeCON"
organizerAlternateName: ""
organizerDescription: ""
organizerEmail: ""
organizerLogo: ""
organizerLink: ""

# Head
metaKeywords: "GeeCON, JVM, Java, Kotlin, Scala"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}

# Speakers List Block
showSessions: true